The config can be None if we set required_workflow to None
see:
```
+ c2cciutils-checks
Traceback (most recent call last):
  File "/usr/local/bin/c2cciutils-checks", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/c2cciutils/scripts/checks.py", line 18, in main
    full_config = c2cciutils.get_config()
  File "/usr/local/lib/python3.8/dist-packages/c2cciutils/__init__.py", line 205, in get_config
    merge(required_workflows, config["checks"]["required_workflows"])
  File "/usr/local/lib/python3.8/dist-packages/c2cciutils/__init__.py", line 39, in merge
    if key not in config:
TypeError: argument of type 'bool' is not iterable
```